// Mocks generated by Mockito 5.4.6 from annotations
// in tabashir/test/helpers/test_helper.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i7;

import 'package:flutter_bloc/flutter_bloc.dart' as _i8;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i6;
import 'package:tabashir/features/profile/presentation/cubit/profile_cubit.dart'
    as _i2;
import 'package:tabashir/features/resume/presentation/cubit/resume_review_cubit.dart'
    as _i4;
import 'package:tabashir/features/resume/presentation/cubit/resume_review_state.dart'
    as _i5;
import 'package:tabashir/features/resume/presentation/cubit/resume_vault_cubit.dart'
    as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeProfileCubit_0 extends _i1.SmartFake implements _i2.ProfileCubit {
  _FakeProfileCubit_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeResumeVaultCubit_1 extends _i1.SmartFake
    implements _i3.ResumeVaultCubit {
  _FakeResumeVaultCubit_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [ResumeReviewCubit].
///
/// See the documentation for Mockito's code generation for more information.
class MockResumeReviewCubit extends _i1.Mock implements _i4.ResumeReviewCubit {
  MockResumeReviewCubit() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.ProfileCubit get profileCubit =>
      (super.noSuchMethod(
            Invocation.getter(#profileCubit),
            returnValue: _FakeProfileCubit_0(
              this,
              Invocation.getter(#profileCubit),
            ),
          )
          as _i2.ProfileCubit);

  @override
  _i3.ResumeVaultCubit get resumeVaultCubit =>
      (super.noSuchMethod(
            Invocation.getter(#resumeVaultCubit),
            returnValue: _FakeResumeVaultCubit_1(
              this,
              Invocation.getter(#resumeVaultCubit),
            ),
          )
          as _i3.ResumeVaultCubit);

  @override
  _i5.ResumeReviewState get state =>
      (super.noSuchMethod(
            Invocation.getter(#state),
            returnValue: _i6.dummyValue<_i5.ResumeReviewState>(
              this,
              Invocation.getter(#state),
            ),
          )
          as _i5.ResumeReviewState);

  @override
  _i7.Stream<_i5.ResumeReviewState> get stream =>
      (super.noSuchMethod(
            Invocation.getter(#stream),
            returnValue: _i7.Stream<_i5.ResumeReviewState>.empty(),
          )
          as _i7.Stream<_i5.ResumeReviewState>);

  @override
  bool get isClosed =>
      (super.noSuchMethod(Invocation.getter(#isClosed), returnValue: false)
          as bool);

  @override
  void updatePersonalInfo({
    String? name,
    String? email,
    String? phone,
    String? location,
    String? linkedin,
  }) => super.noSuchMethod(
    Invocation.method(#updatePersonalInfo, [], {
      #name: name,
      #email: email,
      #phone: phone,
      #location: location,
      #linkedin: linkedin,
    }),
    returnValueForMissingStub: null,
  );

  @override
  void updateSummary(String? summary) => super.noSuchMethod(
    Invocation.method(#updateSummary, [summary]),
    returnValueForMissingStub: null,
  );

  @override
  void addExperience(Map<String, dynamic>? experience) => super.noSuchMethod(
    Invocation.method(#addExperience, [experience]),
    returnValueForMissingStub: null,
  );

  @override
  void removeExperience(int? index) => super.noSuchMethod(
    Invocation.method(#removeExperience, [index]),
    returnValueForMissingStub: null,
  );

  @override
  void updateSkills(List<String>? skills) => super.noSuchMethod(
    Invocation.method(#updateSkills, [skills]),
    returnValueForMissingStub: null,
  );

  @override
  _i7.Future<void> confirmAndSave() =>
      (super.noSuchMethod(
            Invocation.method(#confirmAndSave, []),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  void emit(_i5.ResumeReviewState? state) => super.noSuchMethod(
    Invocation.method(#emit, [state]),
    returnValueForMissingStub: null,
  );

  @override
  void onChange(_i8.Change<_i5.ResumeReviewState>? change) =>
      super.noSuchMethod(
        Invocation.method(#onChange, [change]),
        returnValueForMissingStub: null,
      );

  @override
  void addError(Object? error, [StackTrace? stackTrace]) => super.noSuchMethod(
    Invocation.method(#addError, [error, stackTrace]),
    returnValueForMissingStub: null,
  );

  @override
  void onError(Object? error, StackTrace? stackTrace) => super.noSuchMethod(
    Invocation.method(#onError, [error, stackTrace]),
    returnValueForMissingStub: null,
  );

  @override
  _i7.Future<void> close() =>
      (super.noSuchMethod(
            Invocation.method(#close, []),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);
}
