#!/usr/bin/env python3
import json
import sys

# Spanish translations for common terms
spanish_translations = {
    "Account": "Cuenta",
    "About Tabashir": "Acerca de Tabashir",
    "Add Resume": "Agregar Currículum",
    "Apply Now": "Aplicar Ahora",
    "Apply to Jobs": "Aplicar a Trabajos",
    "AI Job Apply": "Aplicación Inteligente de Trabajos",
    "Email": "Correo Electrónico",
    "Password": "Contraseña",
    "Login": "Iniciar Sesión",
    "Sign Up": "Registrarse",
    "Profile": "Perfil",
    "Settings": "Configuración",
    "Logout": "Cerrar Sesión",
    "Jobs": "Trabajos",
    "Home": "Inicio",
    "Notifications": "Notificaciones",
    "Search": "Buscar",
    "Edit Profile": "Editar Perfil",
    "Save": "Guardar",
    "Cancel": "Cancelar",
    "Name": "Nombre",
    "Phone": "Teléfono",
    "Location": "Ubicación",
    "Company": "Empresa",
    "Education": "Educación",
    "Job Title": "Título del Trabajo",
    "LinkedIn Profile": "Perfil de LinkedIn",
    "Nationality": "Nacionalidad",
    "Gender": "Género",
    "Change Password": "Cambiar Contraseña",
    "Current Password": "Contraseña Actual",
    "New Password": "Nueva Contraseña",
    "Confirm Password": "Confirmar Contraseña",
    "Personal Information": "Información Personal",
    "Professional Details": "Detalles Profesionales",
    "My Profile": "Mi Perfil",
    "Resume Vault": "Bóveda de Currículums",
    "Create with AI": "Crear con IA",
    "Use Resume Builder": "Usar Constructor de Currículum",
    "Upload from Device": "Subir desde Dispositivo",
    "Review": "Revisar",
    "Submit": "Enviar",
    "Success": "Éxito",
    "Error": "Error",
    "Warning": "Advertencia",
    "Info": "Información",
    "Yes": "Sí",
    "No": "No",
    "OK": "OK",
    "Close": "Cerrar",
    "Back": "Atrás",
    "Next": "Siguiente",
    "Continue": "Continuar",
    "Finish": "Finalizar",
    "Skip": "Omitir",
    "Help": "Ayuda",
    "Support": "Soporte",
    "Contact": "Contacto",
    "About": "Acerca de",
    "Privacy Policy": "Política de Privacidad",
    "Terms of Service": "Términos de Servicio",
    "Version": "Versión",
    "Loading": "Cargando",
    "Please wait": "Por favor espere",
    "Retry": "Reintentar",
    "Refresh": "Actualizar",
    "Delete": "Eliminar",
    "Edit": "Editar",
    "View": "Ver",
    "Share": "Compartir",
    "Copy": "Copiar",
    "Paste": "Pegar",
    "Select": "Seleccionar",
    "Choose": "Elegir",
    "Select All": "Seleccionar Todo",
    "Deselect": "Deseleccionar",
    "All": "Todo",
    "None": "Ninguno",
    "More": "Más",
    "Less": "Menos",
    "Show": "Mostrar",
    "Hide": "Ocultar",
    "Visible": "Visible",
    "Hidden": "Oculto",
    "Enabled": "Habilitado",
    "Disabled": "Deshabilitado",
    "Active": "Activo",
    "Inactive": "Inactivo",
    "Online": "En línea",
    "Offline": "Fuera de línea",
    "Yes, I agree": "Sí, estoy de acuerdo",
    "I agree to the": "Acepto los",
    "Terms and Conditions": "Términos y Condiciones",
    "Privacy Policy and Terms": "Política de Privacidad y Términos",
    "Sign in": "Iniciar sesión",
    "Sign out": "Cerrar sesión",
    "Create account": "Crear cuenta",
    "Forgot password": "Olvidé mi contraseña",
    "Reset password": "Restablecer contraseña",
    "Send": "Enviar",
    "Search jobs": "Buscar trabajos",
    "Filter": "Filtrar",
    "Sort by": "Ordenar por",
    "Date": "Fecha",
    "Relevance": "Relevancia",
    "Salary": "Salario",
    "Apply": "Aplicar",
    "Applied": "Aplicado",
    "Save job": "Guardar trabajo",
    "Saved": "Guardado",
    "Job details": "Detalles del trabajo",
    "Company details": "Detalles de la empresa",
    "Job description": "Descripción del trabajo",
    "Requirements": "Requisitos",
    "Responsibilities": "Responsabilidades",
    "Benefits": "Beneficios",
    "Skills": "Habilidades",
    "Experience": "Experiencia",
    "Education": "Educación",
    "Certification": "Certificación",
    "Language": "Idioma",
    "Arabic": "Árabe",
    "English": "Inglés",
    "Spanish": "Español",
    "French": "Francés",
    "German": "Alemán",
    "Italian": "Italiano",
    "Portuguese": "Portugués",
    "Russian": "Ruso",
    "Chinese": "Chino",
    "Japanese": "Japonés",
    "Korean": "Coreano",
    "Hindi": "Hindi",
    "Urdu": "Urdu",
    "Turkish": "Turco",
    "Persian": "Persa",
    "Dutch": "Holandés",
    "Swedish": "Sueco",
    "Norwegian": "Noruego",
    "Danish": "Danés",
    "Polish": "Polaco",
    "Czech": "Checo",
    "Hungarian": "Húngaro",
    "Romanian": "Rumano",
    "Bulgarian": "Búlgaro",
    "Croatian": "Croata",
    "Serbian": "Serbio",
    "Greek": "Griego",
    "Hebrew": "Hebreo",
    "Thai": "Tailandés",
    "Vietnamese": "Vietnamita",
    "Indonesian": "Indonesio",
    "Malay": "Malayo",
    "Tagalog": "Tagalo",
    "Swahili": "Swahili",
    "Zulu": "Zulú",
    "Afrikaans": "Afrikáans",
    "Ready to apply?": "¿Listo para aplicar?",
    "Review your application details before submitting.": "Revisa los detalles de tu solicitud antes de enviar.",
    "Resumes": "Currículums",
    "Positions": "Posiciones",
    "Cities": "Ciudades",
    "Jobs Found": "Trabajos Encontrados",
    "matching roles": "roles coincidentes",
    "I'm": "Estoy",
    "confident": "confiado",
    "these roles fit your profile.": "de que estos roles se ajusten a tu perfil.",
    "Applying to": "Aplicando a",
    "jobs may take": "trabajos puede tomar",
    "You'll get a report after.": "Recibirás un informe después.",
    "Apply to": "Aplicar a",
    "Jobs Now": "Trabajos Ahora",
    "Edit Preferences": "Editar Preferencias",
    "Create New with AI": "Crear Nuevo con IA",
    "Use Existing Resume": "Usar Currículum Existente",
    "Skip this step": "Omitir este paso",
    "What's your target role?": "¿Cuál es tu rol objetivo?",
    "Select the positions you're interested in": "Selecciona las posiciones que te interesan",
    "Next: Select Locations": "Siguiente: Seleccionar Ubicaciones",
    "What locations do you prefer?": "¿Qué ubicaciones prefieres?",
    "Choose cities where you'd like to work": "Elige las ciudades donde te gustaría trabajar",
    "Next: Review": "Siguiente: Revisar",
    "Almost done! Just a few more details.": "¡Casi listo! Solo faltan algunos detalles.",
    "Add any additional information you'd like to share.": "Agrega cualquier información adicional que te gustaría compartir.",
    "Next: Review": "Siguiente: Revisar",
    "Personal Details": "Detalles Personales",
    "First Name": "Nombre",
    "Last Name": "Apellido",
    "Date of Birth": "Fecha de Nacimiento",
    "Nationality": "Nacionalidad",
    "Gender": "Género",
    "Select Gender": "Seleccionar Género",
    "Male": "Masculino",
    "Female": "Femenino",
    "Other": "Otro",
    "Prefer not to say": "Prefiero no decir",
    "Select Nationality": "Seleccionar Nacionalidad",
    "Upload Resume": "Subir Currículum",
    "Your CV/Resume": "Tu CV/Currículum",
    "Drag & drop your resume here or click to browse": "Arrastra y suelta tu currículum aquí o haz clic para navegar",
    "Next": "Siguiente",
    "Target Roles": "Roles Objetivo",
    "Location Preferences": "Preferencias de Ubicación",
    "AI Job Application": "Solicitud de Trabajo con IA",
    "Great choice! Now let's find your dream job.": "¡Excelente elección! Ahora encontremos tu trabajo de ensueño.",
    "Find Jobs": "Encontrar Trabajos",
    "Create Resume": "Crear Currículum",
    "AI Resume Builder": "Constructor de Currículum con IA",
    "Build a professional resume with AI assistance": "Construye un currículum profesional con asistencia de IA",
    "Get Started": "Comenzar",
    "Resume Builder": "Constructor de Currículum",
    "Build your resume from scratch": "Construye tu currículum desde cero",
    "Resume Vault": "Bóveda de Currículums",
    "View and manage all your resumes": "Ver y gestionar todos tus currículums",
    "Open Vault": "Abrir Bóveda",
    "No resumes yet": "Aún no hay currículums",
    "Create your first resume to get started": "Crea tu primer currículum para comenzar",
    "Create Resume": "Crear Currículum",
    "Resume": "Currículum",
    "Select Resume": "Seleccionar Currículum",
    "Choose which resume to use for this application": "Elige qué currículum usar para esta solicitud",
    "Continue": "Continuar",
    "No resumes available": "No hay currículums disponibles",
    "You need to create a resume first": "Necesitas crear un currículum primero",
    "Create Now": "Crear Ahora",
    "Job Search": "Búsqueda de Trabajo",
    "Find your next opportunity": "Encuentra tu próxima oportunidad",
    "Search": "Buscar",
    "Filters": "Filtros",
    "Location": "Ubicación",
    "Job Type": "Tipo de Trabajo",
    "Remote": "Remoto",
    "Hybrid": "Híbrido",
    "On-site": "Presencial",
    "Full-time": "Tiempo Completo",
    "Part-time": "Medio Tiempo",
    "Contract": "Contrato",
    "Internship": "Prácticas",
    "Salary Range": "Rango de Salario",
    "Experience Level": "Nivel de Experiencia",
    "Entry Level": "Nivel de Entrada",
    "Mid Level": "Nivel Medio",
    "Senior Level": "Nivel Senior",
    "Executive": "Ejecutivo",
    "Clear Filters": "Limpiar Filtros",
    "Apply Filters": "Aplicar Filtros",
    "No jobs found": "No se encontraron trabajos",
    "Try adjusting your search criteria": "Intenta ajustar tus criterios de búsqueda",
    "Job": "Trabajo",
    "Company": "Empresa",
    "Location": "Ubicación",
    "Salary": "Salario",
    "Posted": "Publicado",
    "ago": "hace",
    "Save": "Guardar",
    "Saved": "Guardado",
    "Apply": "Aplicar",
    "View Details": "Ver Detalles",
    "Job Details": "Detalles del Trabajo",
    "Apply Now": "Aplicar Ahora",
    "Save Job": "Guardar Trabajo",
    "Share": "Compartir",
    "Job Description": "Descripción del Trabajo",
    "Requirements": "Requisitos",
    "Responsibilities": "Responsabilidades",
    "Benefits": "Beneficios",
    "About the Company": "Acerca de la Empresa",
    "Company Size": "Tamaño de la Empresa",
    "Industry": "Industria",
    "Founded": "Fundado",
    "Website": "Sitio Web",
    "Similar Jobs": "Trabajos Similares",
    "Applications": "Solicitudes",
    "Your Job Applications": "Tus Solicitudes de Trabajo",
    "View and track your job applications": "Ver y seguir tus solicitudes de trabajo",
    "No applications yet": "Aún no hay solicitudes",
    "Start applying to jobs to see them here": "Comienza a aplicar a trabajos para verlos aquí",
    "Find Jobs": "Encontrar Trabajos",
    "Application": "Solicitud",
    "Status": "Estado",
    "Pending": "Pendiente",
    "Under Review": "En Revisión",
    "Interview": "Entrevista",
    "Accepted": "Aceptado",
    "Rejected": "Rechazado",
    "Withdrawn": "Retirado",
    "Applied": "Aplicado",
    "Date Applied": "Fecha de Aplicación",
    "Company": "Empresa",
    "View Application": "Ver Solicitud",
    "Withdraw Application": "Retirar Solicitud",
    "Notifications": "Notificaciones",
    "Stay updated with your job search": "Mantente actualizado con tu búsqueda de trabajo",
    "Mark all as read": "Marcar todo como leído",
    "No notifications yet": "Aún no hay notificaciones",
    "You're all caught up!": "¡Estás al día!",
    "New notification": "Nueva notificación",
    "ago": "hace",
    "View": "Ver",
    "Settings": "Configuración",
    "Profile Settings": "Configuración del Perfil",
    "Account Settings": "Configuración de la Cuenta",
    "Notification Settings": "Configuración de Notificaciones",
    "Privacy Settings": "Configuración de Privacidad",
    "Help & Support": "Ayuda y Soporte",
    "About": "Acerca de",
    "Version": "Versión",
    "Dark Mode": "Modo Oscuro",
    "Language": "Idioma",
    "English": "Inglés",
    "Arabic": "Árabe",
    "Spanish": "Español",
    "Email Notifications": "Notificaciones por Correo",
    "Push Notifications": "Notificaciones Push",
    "Marketing Emails": "Correos de Marketing",
    "Privacy": "Privacidad",
    "Data Usage": "Uso de Datos",
    "Terms": "Términos",
    "Logout": "Cerrar Sesión",
    "Are you sure?": "¿Estás seguro?",
    "You can always sign back in": "Siempre puedes volver a iniciar sesión",
    "Cancel": "Cancelar",
    "Sign Out": "Cerrar Sesión",
}

def translate_to_spanish(input_file, output_file):
    with open(input_file, 'r', encoding='utf-8') as f:
        data = json.load(f)

    translated_data = {}
    for key, value in data.items():
        # If the value matches a key in our translation dict, use the Spanish translation
        if value in spanish_translations:
            translated_data[key] = spanish_translations[value]
        # Otherwise, if the value is the same as the key, translate the key
        elif value == key:
            translated_data[key] = spanish_translations.get(key, f"[ES] {key}")
        # If it's a template string with variables, keep it as is
        elif '$' in value or '{' in value:
            translated_data[key] = value
        # If it's a color code or regex, keep it as is
        elif value.startswith('#') or value.startswith('^') or value.startswith('[') or value.startswith('\\'):
            translated_data[key] = value
        # If it's a number or special character, keep it as is
        elif value.isdigit() or all(c in '+-()[]{}.,:;@' for c in value):
            translated_data[key] = value
        # Otherwise, wrap with [ES] to indicate translation needed
        else:
            # Try to find a partial match
            found = False
            for en, es in spanish_translations.items():
                if en.lower() in value.lower() or value.lower() in en.lower():
                    translated_data[key] = es
                    found = True
                    break
            if not found:
                translated_data[key] = f"[ES] {key}"

    with open(output_file, 'w', encoding='utf-8') as f:
        json.dump(translated_data, f, ensure_ascii=False, indent=2)

    print(f"Translation complete! {len(translated_data)} keys translated to Spanish.")

if __name__ == "__main__":
    input_file = "/Users/Apple/Documents/tabashir/tabashir/assets/lang/en.json"
    output_file = "/Users/Apple/Documents/tabashir/tabashir/assets/lang/es.json"

    translate_to_spanish(input_file, output_file)
