#!/usr/bin/env python3
import json
import sys

# Arabic translations for common terms
arabic_translations = {
    "Account": "الحساب",
    "About Tabashir": "نبذة عن تباشير",
    "Add Resume": "إضافة سيرة ذاتية",
    "Apply Now": "التقدم الآن",
    "Apply to Jobs": "التقدم للوظائف",
    "AI Job Apply": "التقديم الذكي للوظائف",
    "Email": "البريد الإلكتروني",
    "Password": "كلمة المرور",
    "Login": "تسجيل الدخول",
    "Sign Up": "إنشاء حساب",
    "Profile": "الملف الشخصي",
    "Settings": "الإعدادات",
    "Logout": "تسجيل الخروج",
    "Jobs": "الوظائف",
    "Home": "الرئيسية",
    "Notifications": "الإشعارات",
    "Search": "بحث",
    "Edit Profile": "تعديل الملف الشخصي",
    "Save": "حفظ",
    "Cancel": "إلغاء",
    "Name": "الاسم",
    "Phone": "الهاتف",
    "Location": "الموقع",
    "Company": "الشركة",
    "Education": "التعليم",
    "Job Title": "المسمى الوظيفي",
    "LinkedIn Profile": "ملف LinkedIn",
    "Nationality": "الجنسية",
    "Gender": "الجنس",
    "Change Password": "تغيير كلمة المرور",
    "Current Password": "كلمة المرور الحالية",
    "New Password": "كلمة المرور الجديدة",
    "Confirm Password": "تأكيد كلمة المرور",
    "Personal Information": "المعلومات الشخصية",
    "Professional Details": "التفاصيل المهنية",
    "My Profile": "ملفي الشخصي",
    "Resume Vault": "مستودع السير الذاتية",
    "Create with AI": "إنشاء بالذكاء الاصطناعي",
    "Use Resume Builder": "استخدام منشئ السيرة الذاتية",
    "Upload from Device": "رفع من الجهاز",
    "Review": "مراجعة",
    "Submit": "إرسال",
    "Success": "نجح",
    "Error": "خطأ",
    "Warning": "تحذير",
    "Info": "معلومات",
    "Yes": "نعم",
    "No": "لا",
    "OK": "موافق",
    "Close": "إغلاق",
    "Back": "رجوع",
    "Next": "التالي",
    "Continue": "متابعة",
    "Finish": "إنهاء",
    "Skip": "تخطي",
    "Help": "مساعدة",
    "Support": "الدعم",
    "Contact": "اتصل بنا",
    "About": "حول",
    "Privacy Policy": "سياسة الخصوصية",
    "Terms of Service": "شروط الخدمة",
    "Version": "الإصدار",
    "Loading": "جاري التحميل",
    "Please wait": "يرجى الانتظار",
    "Retry": "إعادة المحاولة",
    "Refresh": "تحديث",
    "Delete": "حذف",
    "Edit": "تعديل",
    "View": "عرض",
    "Share": "مشاركة",
    "Copy": "نسخ",
    "Paste": "لصق",
    "Select": "اختر",
    "Choose": "اختر",
    "Select All": "اختيار الكل",
    "Deselect": "إلغاء الاختيار",
    "All": "الكل",
    "None": "لا شيء",
    "More": "المزيد",
    "Less": "أقل",
    "Show": "إظهار",
    "Hide": "إخفاء",
    "Visible": "مرئي",
    "Hidden": "مخفي",
    "Enabled": "مفعل",
    "Disabled": "معطل",
    "Active": "نشط",
    "Inactive": "غير نشط",
    "Online": "متصل",
    "Offline": "غير متصل",
    "Yes, I agree": "نعم، أوافق",
    "I agree to the": "أوافق على",
    "Terms and Conditions": "الشروط والأحكام",
    "Privacy Policy and Terms": "سياسة الخصوصية والشروط",
    "Sign in": "تسجيل الدخول",
    "Sign out": "تسجيل الخروج",
    "Create account": "إنشاء حساب",
    "Forgot password": "نسيت كلمة المرور",
    "Reset password": "إعادة تعيين كلمة المرور",
    "Send": "إرسال",
    "Search jobs": "البحث عن وظائف",
    "Filter": "تصفية",
    "Sort by": "ترتيب حسب",
    "Date": "التاريخ",
    "Relevance": "الصلة",
    "Salary": "الراتب",
    "Apply": "تقدم",
    "Applied": "تم التقديم",
    "Save job": "حفظ الوظيفة",
    "Saved": "محفوظ",
    "Job details": "تفاصيل الوظيفة",
    "Company details": "تفاصيل الشركة",
    "Job description": "وصف الوظيفة",
    "Requirements": "المتطلبات",
    "Responsibilities": "المسؤوليات",
    "Benefits": "المزايا",
    "Skills": "المهارات",
    "Experience": "الخبرة",
    "Education": "التعليم",
    "Certification": "الشهادة",
    "Language": "اللغة",
    "Arabic": "العربية",
    "English": "الإنجليزية",
    "Spanish": "الإسبانية",
    "French": "الفرنسية",
    "German": "الألمانية",
    "Italian": "الإيطالية",
    "Portuguese": "البرتغالية",
    "Russian": "الروسية",
    "Chinese": "الصينية",
    "Japanese": "اليابانية",
    "Korean": "الكورية",
    "Hindi": "الهندية",
    "Urdu": "الأردية",
    "Turkish": "التركية",
    "Persian": "الفارسية",
    "Dutch": "الهولندية",
    "Swedish": "السويدية",
    "Norwegian": "النرويجية",
    "Danish": "الدنماركية",
    "Polish": "البولندية",
    "Czech": "التشيكية",
    "Hungarian": "المجرية",
    "Romanian": "الرومانية",
    "Bulgarian": "البلغارية",
    "Croatian": "الكرواتية",
    "Serbian": "الصربية",
    "Greek": "اليونانية",
    "Hebrew": "العبرية",
    "Thai": "التايلاندية",
    "Vietnamese": "الفيتنامية",
    "Indonesian": "الإندونيسية",
    "Malay": "الماليزية",
    "Tagalog": "التاغالوغية",
    "Swahili": "السواحيلية",
    "Zulu": "الزولو",
    "Afrikaans": "الأفريقانية",
    "United Arab Emirates": "الإمارات العربية المتحدة",
    "Saudi Arabia": "المملكة العربية السعودية",
    "Qatar": "قطر",
    "Kuwait": "الكويت",
    "Bahrain": "البحرين",
    "Oman": "عمان",
    "Jordan": "الأردن",
    "Lebanon": "لبنان",
    "Syria": "سوريا",
    "Iraq": "العراق",
    "Yemen": "اليمن",
    "Palestine": "فلسطين",
    "Egypt": "مصر",
    "Libya": "ليبيا",
    "Tunisia": "تونس",
    "Algeria": "الجزائر",
    "Morocco": "المغرب",
    "Sudan": "السودان",
    "Djibouti": "جيبوتي",
    "Somalia": "الصومال",
    "Comoros": "جزر القمر",
    "Mauritania": "موريتانيا",
    "Mali": "مالي",
    "Niger": "النيجر",
    "Chad": "تشاد",
    "Central African Republic": "جمهورية أفريقيا الوسطى",
    "Cameroon": "الكاميرون",
    "Equatorial Guinea": "غينيا الاستوائية",
    "Gabon": "الغابون",
    "Republic of the Congo": "جمهورية الكونغو",
    "Democratic Republic of the Congo": "جمهورية الكونغو الديمقراطية",
    "Angola": "أنغولا",
    "Zambia": "زامبيا",
    "Malawi": "مالاوي",
    "Mozambique": "موزمبيق",
    "Zimbabwe": "زيمبابوي",
    "Botswana": "بوتسوانا",
    "Namibia": "ناميبيا",
    "South Africa": "جنوب أفريقيا",
    "Eswatini": "إيسواتيني",
    "Lesotho": "ليسوتو",
    "Madagascar": "مدغشقر",
    "Mauritius": "موريشيوس",
    "Seychelles": "سيشل",
    "Comoros": "جزر القمر",
    "Maldives": "المالديف",
    "Sri Lanka": "سريلانكا",
    "Bangladesh": "بنغلاديش",
    "Pakistan": "باكستان",
    "Afghanistan": "أفغانستان",
    "Iran": "إيران",
    "Armenia": "أرمينيا",
    "Azerbaijan": "أذربيجان",
    "Georgia": "جورجيا",
    "Kazakhstan": "كازاخستان",
    "Kyrgyzstan": "قيرغيزستان",
    "Tajikistan": "طاجيكستان",
    "Turkmenistan": "تركمانستان",
    "Uzbekistan": "أوزبكستان",
    "Mongolia": "منغوليا",
    "North Korea": "كوريا الشمالية",
    "South Korea": "كوريا الجنوبية",
    "Taiwan": "تايوان",
    "Hong Kong": "هونغ كونغ",
    "Macau": "ماكاو",
    "Singapore": "سنغافورة",
    "Brunei": "بروناي",
    "East Timor": "تيمور الشرقية",
    "Papua New Guinea": "بابوا غينيا الجديدة",
    "Fiji": "فيجي",
    "Solomon Islands": "جزر سولومون",
    "Vanuatu": "فانواتو",
    "New Caledonia": "كاليدونيا الجديدة",
    "Samoa": "ساموا",
    "Tonga": "تونغا",
    "Kiribati": "كيريباتي",
    "Tuvalu": "توفالو",
    "Nauru": "ناورو",
    "Palau": "بالاو",
    "Marshall Islands": "جزر مارشال",
    "Micronesia": "ميكرونيزيا",
    "Cook Islands": "جزر كوك",
    "Niue": "نيي",
    "Tokelau": "توكيلاو",
    "American Samoa": "ساموا الأمريكية",
    "Guam": "غوام",
    "Northern Mariana Islands": "جزر ماريانا الشمالية",
    "Puerto Rico": "بورتوريكو",
    "US Virgin Islands": "جزر العذراء الأمريكية",
    "British Virgin Islands": "جزر العذراء البريطانية",
    "Anguilla": "أنغويلا",
    "Montserrat": "مونتسيرات",
    "Guadeloupe": "غوادلوب",
    "Martinique": "مارتينيك",
    "Saint Barthélemy": "سان بارتليمي",
    "Saint Martin": "سان مارتن",
    "Saint Pierre and Miquelon": "سان بيير وميكيلون",
    "Saint Helena": "سانت هيلانة",
    "Falkland Islands": "جزر فوكلاند",
    "French Guiana": "غويانا الفرنسية",
    "Suriname": "سورينام",
    "Guyana": "غيانا",
    "Venezuela": "فنزويلا",
    "Brazil": "البرازيل",
    "Colombia": "كولومبيا",
    "Ecuador": "الإكوادور",
    "Peru": "بيرو",
    "Bolivia": "بوليفيا",
    "Paraguay": "باراغواي",
    "Uruguay": "أوروغواي",
    "Argentina": "الأرجنتين",
    "Chile": "تشيلي",
    "Mexico": "المكسيك",
    "Guatemala": "غواتيمالا",
    "Belize": "بليز",
    "El Salvador": "السلفادور",
    "Honduras": "هندوراس",
    "Nicaragua": "نيكاراغوا",
    "Costa Rica": "كوستاريكا",
    "Panama": "بنما",
    "Cuba": "كوبا",
    "Jamaica": "جامايكا",
    "Haiti": "هايتي",
    "Dominican Republic": "جمهورية الدومينيكان",
    "Bahamas": "البهاما",
    "Barbados": "باربادوس",
    "Trinidad and Tobago": "ترينيداد وتوباغو",
    "Grenada": "غرينادا",
    "Saint Vincent and the Grenadines": "سانت فنسنت وجزر غرينادين",
    "Saint Lucia": "سانت لوسيا",
    "Dominica": "دومينيكا",
    "Antigua and Barbuda": "أنتيغوا وباربودا",
    "Saint Kitts and Nevis": "سانت كيتس ونيفيس",
    "Canada": "كندا",
    "United States": "الولايات المتحدة",
    "United Kingdom": "المملكة المتحدة",
    "Ireland": "أيرلندا",
    "Iceland": "أيسلندا",
    "Greenland": "غرينلاند",
    "Faroe Islands": "جزر فارو",
    "Estonia": "إستونيا",
    "Latvia": "لاتفيا",
    "Lithuania": "ليتوانيا",
    "Belarus": "بيلاروسيا",
    "Ukraine": "أوكرانيا",
    "Moldova": "مولدوفا",
    "Russia": "روسيا",
    "Finland": "فنلندا",
    "Austria": "النمسا",
    "Switzerland": "سويسرا",
    "Liechtenstein": "ليختنشتاين",
    "Slovakia": "سلوفاكيا",
    "Slovenia": "سلوفينيا",
    "Bosnia and Herzegovina": "البوسنة والهرسك",
    "Montenegro": "الجبل الأسود",
    "Albania": "ألبانيا",
    "North Macedonia": "شمال مقدونيا",
    "Kosovo": "كوسوفو",
    "Serbia": "صربيا",
    "Croatia": "كرواتيا",
    "Italy": "إيطاليا",
    "Vatican City": "الفاتيكان",
    "San Marino": "سان مارينو",
    "Monaco": "موناكو",
    "France": "فرنسا",
    "Belgium": "بلجيكا",
    "Luxembourg": "لوكسمبورغ",
    "Netherlands": "هولندا",
    "Germany": "ألمانيا",
    "Spain": "إسبانيا",
    "Portugal": "البرتغال",
    "Andorra": "أندورا",
    "Gibraltar": "جبل طارق",
    "Morocco": "المغرب",
    "Algeria": "الجزائر",
    "Tunisia": "تونس",
    "Libya": "ليبيا",
    "Egypt": "مصر",
    "Sudan": "السودان",
    "Ethiopia": "إثيوبيا",
    "Eritrea": "إريتريا",
    "Djibouti": "جيبوتي",
    "Somalia": "الصومال",
    "Kenya": "كينيا",
    "Uganda": "أوغندا",
    "Rwanda": "رواندا",
    "Burundi": "بوروندي",
    "Tanzania": "تنزانيا",
    "Democratic Republic of the Congo": "جمهورية الكونغو الديمقراطية",
    "Republic of the Congo": "جمهورية الكونغو",
    "Central African Republic": "جمهورية أفريقيا الوسطى",
    "Cameroon": "الكاميرون",
    "Equatorial Guinea": "غينيا الاستوائية",
    "Gabon": "الغابون",
    "São Tomé and Príncipe": "ساو تومي وبرينسيبي",
    "Nigeria": "نيجيريا",
    "Niger": "النيجر",
    "Chad": "تشاد",
    "Sudan": "السودان",
    "South Sudan": "جنوب السودان",
    "Ethiopia": "إثيوبيا",
    "Eritrea": "إريتريا",
    "Somalia": "الصومال",
    "Kenya": "كينيا",
    "Uganda": "أوغندا",
    "Rwanda": "رواندا",
    "Burundi": "بوروندي",
    "Tanzania": "تنزانيا",
    "Zambia": "زامبيا",
    "Malawi": "مالاوي",
    "Mozambique": "موزمبيق",
    "Zimbabwe": "زيمبابوي",
    "Botswana": "بوتسوانا",
    "Namibia": "ناميبيا",
    "South Africa": "جنوب أفريقيا",
    "Eswatini": "إيسواتيني",
    "Lesotho": "ليسوتو",
    "Madagascar": "مدغشقر",
    "Mauritius": "موريشيوس",
    "Seychelles": "سيشل",
    "Comoros": "جزر القمر",
    "Reunion": "ريونيون",
    "Mayotte": "مايوت",
    "Saint Helena": "سانت هيلانة",
    "Ascension Island": "جزيرة أسينشن",
    "Tristan da Cunha": "ترستان دا كونا",
    "Australia": "أستراليا",
    "New Zealand": "نيوزيلندا",
    "Fiji": "فيجي",
    "Papua New Guinea": "بابوا غينيا الجديدة",
    "Solomon Islands": "جزر سولومون",
    "Vanuatu": "فانواتو",
    "New Caledonia": "كاليدونيا الجديدة",
    "Samoa": "ساموا",
    "Tonga": "تونغا",
    "Kiribati": "كيريباتي",
    "Tuvalu": "توفالو",
    "Nauru": "ناورو",
    "Palau": "بالاو",
    "Marshall Islands": "جزر مارشال",
    "Micronesia": "ميكرونيزيا",
    "Cook Islands": "جزر كوك",
    "Niue": "نيي",
    "Tokelau": "توكيلاو",
    "French Polynesia": "بولينيزيا الفرنسية",
    "Wallis and Futuna": "واليس وفوتونا",
    "American Samoa": "ساموا الأمريكية",
    "Guam": "غوام",
    "Northern Mariana Islands": "جزر ماريانا الشمالية",
    "Puerto Rico": "بورتوريكو",
    "US Virgin Islands": "جزر العذراء الأمريكية",
    "British Virgin Islands": "جزر العذراء البريطانية",
    "Anguilla": "أنغويلا",
    "Montserrat": "مونتسيرات",
    "Guadeloupe": "غوادلوب",
    "Martinique": "مارتينيك",
    "Saint Barthélemy": "سان بارتليمي",
    "Saint Martin": "سان مارتن",
    "Saint Pierre and Miquelon": "سان بيير وميكيلون",
    "Saint Helena": "سانت هيلانة",
    "Falkland Islands": "جزر فوكلاند",
    "French Guiana": "غويانا الفرنسية",
    "Suriname": "سورينام",
    "Guyana": "غيانا",
    "Venezuela": "فنزويلا",
    "Brazil": "البرازيل",
    "Colombia": "كولومبيا",
    "Ecuador": "الإكوادور",
    "Peru": "بيرو",
    "Bolivia": "بوليفيا",
    "Paraguay": "باراغواي",
    "Uruguay": "أوروغواي",
    "Argentina": "الأرجنتين",
    "Chile": "تشيلي",
    "Mexico": "المكسيك",
    "Guatemala": "غواتيمالا",
    "Belize": "بليز",
    "El Salvador": "السلفادور",
    "Honduras": "هندوراس",
    "Nicaragua": "نيكاراغوا",
    "Costa Rica": "كوستاريكا",
    "Panama": "بنما",
    "Cuba": "كوبا",
    "Jamaica": "جامايكا",
    "Haiti": "هايتي",
    "Dominican Republic": "جمهورية الدومينيكان",
    "Bahamas": "البهاما",
    "Barbados": "باربادوس",
    "Trinidad and Tobago": "ترينيداد وتوباغو",
    "Grenada": "غرينادا",
    "Saint Vincent and the Grenadines": "سانت فنسنت وجزر غرينادين",
    "Saint Lucia": "سانت لوسيا",
    "Dominica": "دومينيكا",
    "Antigua and Barbuda": "أنتيغوا وباربودا",
    "Saint Kitts and Nevis": "سانت كيتس ونيفيس",
    "Canada": "كندا",
    "United States": "الولايات المتحدة",
    "United Kingdom": "المملكة المتحدة",
    "Ireland": "أيرلندا",
    "Iceland": "أيسلندا",
    "Greenland": "غرينلاند",
    "Faroe Islands": "جزر فارو",
    "Estonia": "إستونيا",
    "Latvia": "لاتفيا",
    "Lithuania": "ليتوانيا",
    "Belarus": "بيلاروسيا",
    "Ukraine": "أوكرانيا",
    "Moldova": "مولدوفا",
    "Russia": "روسيا",
    "Finland": "فنلندا",
    "Austria": "النمسا",
    "Switzerland": "سويسرا",
    "Liechtenstein": "ليختنشتاين",
    "Slovakia": "سلوفاكيا",
    "Slovenia": "سلوفينيا",
    "Bosnia and Herzegovina": "البوسنة والهرسك",
    "Montenegro": "الجبل الأسود",
    "Albania": "ألبانيا",
    "North Macedonia": "شمال مقدونيا",
    "Kosovo": "كوسوفو",
    "Serbia": "صربيا",
    "Croatia": "كرواتيا",
    "Italy": "إيطاليا",
    "Vatican City": "الفاتيكان",
    "San Marino": "سان مارينو",
    "Monaco": "موناكو",
    "France": "فرنسا",
    "Belgium": "بلجيكا",
    "Luxembourg": "لوكسمبورغ",
    "Netherlands": "هولندا",
    "Germany": "ألمانيا",
    "Spain": "إسبانيا",
    "Portugal": "البرتغال",
    "Andorra": "أندورا",
    "Gibraltar": "جبل طارق",
}

def translate_to_arabic(input_file, output_file):
    with open(input_file, 'r', encoding='utf-8') as f:
        data = json.load(f)

    translated_data = {}
    for key, value in data.items():
        # If the value matches a key in our translation dict, use the Arabic translation
        if value in arabic_translations:
            translated_data[key] = arabic_translations[value]
        # Otherwise, if the value is the same as the key, translate the key
        elif value == key:
            translated_data[key] = arabic_translations.get(key, f"[AR] {key}")
        # If it's a template string with variables, keep it as is
        elif '$' in value or '{' in value:
            translated_data[key] = value
        # If it's a color code or regex, keep it as is
        elif value.startswith('#') or value.startswith('^') or value.startswith('[') or value.startswith('\\'):
            translated_data[key] = value
        # If it's a number or special character, keep it as is
        elif value.isdigit() or all(c in '+-()[]{}.,:;@' for c in value):
            translated_data[key] = value
        # Otherwise, wrap with [AR] to indicate translation needed
        else:
            # Try to find a partial match
            found = False
            for en, ar in arabic_translations.items():
                if en.lower() in value.lower() or value.lower() in en.lower():
                    translated_data[key] = ar
                    found = True
                    break
            if not found:
                translated_data[key] = f"[AR] {key}"

    with open(output_file, 'w', encoding='utf-8') as f:
        json.dump(translated_data, f, ensure_ascii=False, indent=2)

    print(f"Translation complete! {len(translated_data)} keys translated to Arabic.")

if __name__ == "__main__":
    input_file = "/Users/Apple/Documents/tabashir/tabashir/assets/lang/en.json"
    output_file = "/Users/Apple/Documents/tabashir/tabashir/assets/lang/ar.json"

    translate_to_arabic(input_file, output_file)
