/// Constants for profile dropdown options
library;

/// List of nationality options
const List<String> nationalityOptions = [
  'Afghan',
  'Albanian',
  'Algerian',
  'American',
  'Argentine',
  'Armenian',
  'Australian',
  'Austrian',
  'Azerbaijani',
  'Bangladeshi',
  'Belarusian',
  'Belgian',
  'Brazilian',
  'British',
  'Bulgarian',
  'Cambodian',
  'Canadian',
  'Chinese',
  'Colombian',
  'Croatian',
  'Cuban',
  'Czech',
  'Danish',
  'Dominican',
  'Dutch',
  'Ecuadorean',
  'Egyptian',
  'Emirati',
  'Ethiopian',
  'Filipino',
  'Finnish',
  'French',
  'Georgian',
  'German',
  'Ghanaian',
  'Greek',
  'Guatemalan',
  'Haitian',
  'Honduran',
  'Hungarian',
  'Icelandic',
  'Indian',
  'Indonesian',
  'Iranian',
  'Iraqi',
  'Irish',
  'Israeli',
  'Italian',
  'Jamaican',
  'Japanese',
  'Jordanian',
  'Kazakh',
  'Kenyan',
  'Kuwaiti',
  'Lebanese',
  'Libyan',
  'Malaysian',
  'Mexican',
  'Moroccan',
  'Nepalese',
  'Nigerian',
  'Norwegian',
  'Pakistani',
  'Panamanian',
  'Peruvian',
  'Polish',
  'Portuguese',
  'Romanian',
  'Russian',
  'Saudi',
  'Serbian',
  'Singaporean',
  'Slovak',
  'Slovenian',
  'Somali',
  'South African',
  'South Korean',
  'Spanish',
  'Sri Lankan',
  'Swedish',
  'Swiss',
  'Syrian',
  'Thai',
  'Tunisian',
  'Turkish',
  'Ukrainian',
  'Venezuelan',
  'Vietnamese',
];

/// List of gender options
const List<String> genderOptions = [
  'Male',
  'Female',
  'Non-binary',
  'Prefer not to say',
];
